#!/usr/bin/env bash
# kubectl-exec-debug — companion script for diagnosing kubectl exec failures
# Generated by create-skill meta-skill.
#
# Usage:
#   ./setup.sh --check NODE [SSH_USER]           # check only, no changes
#   ./setup.sh --apply NODE [SSH_USER] [CONFIG]  # apply fix to node
#   ./setup.sh --test NODE [SSH_USER] POD_NAME   # test kubectl exec

set -euo pipefail

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

KUBELET_CONFIG_PATH="/var/lib/kubelet/config.yaml"
KUBELET_CONFIG_FIXED='apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
staticPodPath: /etc/kubernetes/manifests
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
    cacheTTL: 2m0s
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

log()  { echo -e "${CYAN}[kubectl-exec-debug]${NC} $*"; }
ok()   { echo -e "${GREEN}[✓]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*"; }
warn() { echo -e "${YELLOW}[⚠]${NC} $*"; }

# ---------------------------------------------------------------------------
# Check Mode
# ---------------------------------------------------------------------------

check_mode() {
  local node="$1"
  local ssh_user="${2:-$USER}"

  log "Checking kubelet on $node as $ssh_user..."

  # Fetch kubelet config
  local config
  config=$(ssh -o StrictHostKeyChecking=accept-new "$ssh_user@$node" \
    "sudo cat $KUBELET_CONFIG_PATH 2>/dev/null" || echo "")

  if [[ -z "$config" ]]; then
    err "Could not fetch kubelet config from $node"
    return 1
  fi

  # Display config
  echo ""
  echo "=== Kubelet Config on $node ==="
  echo "$config"
  echo ""

  # Run checks
  echo "=== Diagnostic Checks ==="

  local issues=0

  if echo "$config" | grep -q "clientCAFile:"; then
    ok "x509.clientCAFile is configured"
  else
    err "MISSING: x509.clientCAFile (CRITICAL)"
    ((issues++))
  fi

  if echo "$config" | grep -q "anonymous:" && echo "$config" | grep -A1 "anonymous:" | grep -q "enabled: false"; then
    ok "anonymous.enabled = false"
  else
    warn "anonymous.enabled should be explicitly set to false"
  fi

  if echo "$config" | grep -q "webhook:"; then
    ok "webhook authentication configured"
  else
    warn "webhook authentication not configured (recommended)"
  fi

  if echo "$config" | grep -q "mode: Webhook"; then
    ok "authorization.mode = Webhook"
  else
    warn "authorization.mode should be Webhook"
  fi

  echo ""
  if [[ $issues -eq 0 ]]; then
    ok "No critical issues found. kubectl exec should work."
    return 0
  else
    err "Found $issues critical issue(s). Use --apply to fix."
    return 1
  fi
}

# ---------------------------------------------------------------------------
# Apply Mode
# ---------------------------------------------------------------------------

apply_mode() {
  local node="$1"
  local ssh_user="${2:-$USER}"

  log "Applying kubelet config fix to $node..."

  # Create temp file with config
  local config_file="/tmp/kubelet-config-$node.yaml"
  echo "$KUBELET_CONFIG_FIXED" > "$config_file"

  log "Uploading config to $node..."
  scp -o StrictHostKeyChecking=accept-new "$config_file" "$ssh_user@$node:/tmp/kubelet-config.yaml" >/dev/null 2>&1

  log "Applying config..."
  ssh -o StrictHostKeyChecking=accept-new "$ssh_user@$node" << 'REMOTE'
    echo "Backing up current config..."
    sudo cp /var/lib/kubelet/config.yaml /var/lib/kubelet/config.yaml.bak || true

    echo "Applying new config..."
    sudo cp /tmp/kubelet-config.yaml /var/lib/kubelet/config.yaml

    echo "Restarting kubelet..."
    sudo systemctl restart kubelet
    sleep 5

    echo "Verifying kubelet status..."
    sudo systemctl is-active kubelet && echo "kubelet is active" || echo "WARNING: kubelet may not be ready"
REMOTE

  ok "Fix applied to $node. Kubelet restarting..."
  rm -f "$config_file"

  return 0
}

# ---------------------------------------------------------------------------
# Test Mode
# ---------------------------------------------------------------------------

test_mode() {
  local node="$1"
  local ssh_user="${2:-$USER}"
  local pod_name="${3:-test}"

  log "Testing kubectl exec on pod: $pod_name"

  if kubectl exec "$pod_name" -- id >/dev/null 2>&1; then
    ok "kubectl exec works!"
    kubectl exec "$pod_name" -- id
    return 0
  else
    err "kubectl exec failed"
    kubectl exec "$pod_name" -- id 2>&1 || true
    return 1
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
  local mode="${1:-}"

  case "$mode" in
    --check)
      if [[ -z "${2:-}" ]]; then
        echo "Usage: kubectl-exec-debug.sh --check NODE [SSH_USER]"
        exit 1
      fi
      check_mode "$2" "${3:-}"
      ;;
    --apply)
      if [[ -z "${2:-}" ]]; then
        echo "Usage: kubectl-exec-debug.sh --apply NODE [SSH_USER]"
        exit 1
      fi
      apply_mode "$2" "${3:-}"
      ;;
    --test)
      if [[ -z "${2:-}" ]]; then
        echo "Usage: kubectl-exec-debug.sh --test NODE [SSH_USER] [POD_NAME]"
        exit 1
      fi
      test_mode "$2" "${3:-}" "${4:-test}"
      ;;
    *)
      cat << 'USAGE'
kubectl-exec-debug — diagnose and fix kubectl exec failures

Usage:
  ./setup.sh --check NODE [SSH_USER]           # diagnose the issue
  ./setup.sh --apply NODE [SSH_USER]           # apply kubelet config fix
  ./setup.sh --test NODE [SSH_USER] [POD]      # test kubectl exec

Example:
  ./setup.sh --check k8s-agent <ssh-user>
  ./setup.sh --apply k8s-agent <ssh-user>
  ./setup.sh --test k8s-agent <ssh-user> test-pod

Environment:
  NODE           IP or hostname of the worker node
  SSH_USER       SSH username (default: current user)
  POD_NAME       Pod name to test exec against (default: test)
USAGE
      exit 0
      ;;
  esac
}

main "$@"
